TRIGGER_NODE = "trigger"
CONDITION_NODE = "condition"
ACTION_NODE = "action"

SUPPORTED_NODE_TYPES = [
    TRIGGER_NODE,
    CONDITION_NODE,
    ACTION_NODE
]

EQUALS = "=="
NOT_EQUALS = "!="
GREATER_THAN = ">"
LESS_THAN = "<"
GREATER_THAN_EQUAL = ">="
LESS_THAN_EQUAL = "<="
CONTAINS = "contains"

SUPPORTED_OPERATORS = [
    EQUALS,
    NOT_EQUALS,
    GREATER_THAN,
    LESS_THAN,
    GREATER_THAN_EQUAL,
    LESS_THAN_EQUAL,
    CONTAINS
]

WORKFLOW_ACTIVE = "active"
WORKFLOW_INACTIVE = "inactive"

EXECUTION_PENDING = "PENDING" 
EXECUTION_RUNNING = "RUNNING" 
EXECUTION_SUCCESS = "SUCCESS" 
EXECUTION_FAILED = "FAILED" 
EXECUTION_RETRYING = "RETRYING"

EXECUTION_STATUS = [
 EXECUTION_PENDING, 
 EXECUTION_RUNNING, 
 EXECUTION_SUCCESS, 
 EXECUTION_FAILED, EXECUTION_RETRYING   
]

QUEUE_PENDING = "PENDING" 
QUEUE_RUNNING = "RUNNING" 
QUEUE_SUCCESS = "SUCCESS" 
QUEUE_FAILED = "FAILED" 
QUEUE_RETRYING = "RETRYING"

QUEUE_STATUS = [
 QUEUE_PENDING, 
 QUEUE_RUNNING, 
 QUEUE_SUCCESS, 
 QUEUE_FAILED, 
 QUEUE_RETRYING   
]

DEFAULT_RETRY_COUNT = 3 
DEFAULT_RETRY_DELAY = 2 
MAX_RETRY_DELAY = 30

GMAIL_SERVICE = "gmail" 
TELEGRAM_SERVICE = "telegram" 
GOOGLE_SHEETS_SERVICE = "google_sheets" 
WEBHOOK_SERVICE = "webhook" 

SUPPORTED_SERVICES = [ 
    GMAIL_SERVICE, 
    TELEGRAM_SERVICE, GOOGLE_SHEETS_SERVICE, WEBHOOK_SERVICE 
    ] 


INTERVAL_SCHEDULE = "interval"    
CRON_SCHEDULE = "cron"   

SUPPORTED_SCHEDULE_TYPES = [ 
    INTERVAL_SCHEDULE, 
    CRON_SCHEDULE ] 

INFO_LOG = "INFO" 
WARNING_LOG = "WARNING" 
ERROR_LOG = "ERROR" 

SUPPORTED_LOG_TYPES = [ 
    INFO_LOG, 
    WARNING_LOG, 
    ERROR_LOG ]