TRIGGER_NODE = "trigger"
CONDITION_NODE = "condition"
ACTION_NODE = "action"

SUPPORTED_NODE_TYPES = [
    TRIGGER_NODE,
    CONDITION_NODE,
    ACTION_NODE
]

EQUALS = "=="
NOT_EQUALS = "!="
GREATER_THAN = ">"
LESS_THAN = "<"
GREATER_THAN_EQUAL = ">="
LESS_THAN_EQUAL = "<="
CONTAINS = "contains"

SUPPORTED_OPERATORS = [
    EQUALS,
    NOT_EQUALS,
    GREATER_THAN,
    LESS_THAN,
    GREATER_THAN_EQUAL,
    LESS_THAN_EQUAL,
    CONTAINS
]

WORKFLOW_ACTIVE = "active"
WORKFLOW_INACTIVE = "inactive"

EXECUTION_PENDING = "pending"
EXECUTION_RUNNING = "running"
EXECUTION_COMPLETED = "completed"
EXECUTION_FAILED = "failed"